run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/aalobaidi/grmcp)
  
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input
  
  golint:
    min-confidence: 0.8
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 120
  
  funlen:
    lines: 80
    statements: 40
  
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 20

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - typecheck
    - path: examples/
      linters:
        - gomnd
        - funlen
    - text: "fieldSchema declared and not used"
      linters:
        - typecheck
  
  max-issues-per-linter: 0
  max-same-issues: 0